version: '3'

services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-php-app
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task
      MYSQL_ROOT_PASSWORD: task
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
